In [1]:
import numpy as np
import os, fnmatch
import random

In [2]:
M = 10
d = 13
mu = np.zeros((M, d))

In [16]:
mu[0].shape

(13,)

In [15]:
mu[3].sum()

0.0

In [21]:
x = np.random.rand(13)
m = np.random.rand(13)

In [27]:
((x - m) ** 2)[0]

0.651420948870744

In [28]:
(x[0] - m[0]) ** 2

0.651420948870744

In [36]:
x = np.random.rand(7, 13)
x.shape

(7, 13)

In [68]:
m_tile = np.tile(m, x.shape)
m.shape, m_tile.shape

((13,), (7, 169))

In [76]:
np.tile(m, (7, 1))

array([[0.93107017, 0.20235118, 0.53828896, 0.41004769, 0.74335263,
        0.37858006, 0.31028135, 0.7919031 , 0.82000593, 0.15042556,
        0.96130977, 0.212971  , 0.66055035],
       [0.93107017, 0.20235118, 0.53828896, 0.41004769, 0.74335263,
        0.37858006, 0.31028135, 0.7919031 , 0.82000593, 0.15042556,
        0.96130977, 0.212971  , 0.66055035],
       [0.93107017, 0.20235118, 0.53828896, 0.41004769, 0.74335263,
        0.37858006, 0.31028135, 0.7919031 , 0.82000593, 0.15042556,
        0.96130977, 0.212971  , 0.66055035],
       [0.93107017, 0.20235118, 0.53828896, 0.41004769, 0.74335263,
        0.37858006, 0.31028135, 0.7919031 , 0.82000593, 0.15042556,
        0.96130977, 0.212971  , 0.66055035],
       [0.93107017, 0.20235118, 0.53828896, 0.41004769, 0.74335263,
        0.37858006, 0.31028135, 0.7919031 , 0.82000593, 0.15042556,
        0.96130977, 0.212971  , 0.66055035],
       [0.93107017, 0.20235118, 0.53828896, 0.41004769, 0.74335263,
        0.37858006, 0.31028

In [45]:
((x - m)**2/2*m).sum(axis=1)

array([0.55273568, 1.18093301, 0.53679196, 0.29639834, 0.71456217,
       0.66646675, 0.5507999 ])

In [52]:
((np.random.rand(13) - m)**2/2*m).sum()

0.8309861312373765

In [64]:
omega = np.random.rand(3)
omega.shape

(3,)

In [85]:
omega

array([0.2934812 , 0.92119416, 0.43661682])

In [98]:
np.tile(omega, (2, 1)).T

array([[0.2934812 , 0.2934812 ],
       [0.92119416, 0.92119416],
       [0.43661682, 0.43661682]])

In [101]:
from scipy.special import logsumexp

In [118]:
a = [np.log(1), np.log(2), np.log(3)]
a = np.tile(a, (2, 1)).T

In [120]:
a

array([[0.        , 0.        ],
       [0.69314718, 0.69314718],
       [1.09861229, 1.09861229]])

In [122]:
logsumexp(a, axis=0)

array([1.79175947, 1.79175947])

In [123]:
omega.shape

(3,)

In [125]:
np.tile(omega, (2, 1)).shape

(2, 3)

In [128]:
M, d

(10, 13)

In [136]:
def logexp(a, b):
  return np.log(np.exp(a-b).sum(axis=0))

In [165]:
omega = np.random.rand(M, 1)
omega.shape

(10, 1)

In [166]:
bs = np.random.rand(M, d)
bs.shape

(10, 13)

In [167]:
alllog = bs + np.log(omega)

In [168]:
(alllog.max(axis=0) + logexp(alllog, alllog.max(axis=0))).sum()

26.202302561646018

In [169]:
m, t = bs.shape
log_omega = np.log(np.tile(omega, (1, t)))  # (M, T)

In [170]:
log_sum = logsumexp(np.multiply(log_omega, bs), axis=0)

In [171]:
log_sum.sum()

24.971167285325755

In [174]:
[1/M for i in range(M)]

[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]

In [201]:
l = np.array([bs[np.random.randint(bs.shape[0])] for i in range(7)])

In [202]:
l.shape

(7, 13)

In [205]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [207]:
-float("inf") == -np.inf

True

In [208]:
bs.shape

(10, 13)

In [212]:
bs.sum(axis=1).reshape(10, 1).shape

(10, 1)

In [216]:
p = np.random.randn(5)
p.shape

(5,)

In [221]:
np.tile(p, 3).reshape(5, 3)

array([[-0.51096461, -1.8398413 ,  0.70163758],
       [-0.75819215,  1.01539381, -0.51096461],
       [-1.8398413 ,  0.70163758, -0.75819215],
       [ 1.01539381, -0.51096461, -1.8398413 ],
       [ 0.70163758, -0.75819215,  1.01539381]])

In [222]:
p

array([-0.51096461, -1.8398413 ,  0.70163758, -0.75819215,  1.01539381])

In [223]:
p ** 2

array([0.26108483, 3.38501602, 0.4922953 , 0.57485533, 1.03102458])

In [227]:
np.zeros((M, 1)).shape[0]

10

In [235]:
loglikes = [np.random.randn(1)[0] for i in range(8)]

In [236]:
len(loglikes)

8

In [237]:
best_indices = np.argsort(-np.array(loglikes))  # -'ves to reverse order

In [238]:
loglikes

[-1.9169613942230468,
 -0.08528746545069094,
 -0.1448665283708884,
 2.1390214444154263,
 0.17601708623957837,
 0.46622249235307717,
 -0.6069613529877534,
 -0.2843883318647938]

In [244]:
best_indices[:3]

array([3, 5, 4])

In [245]:
np.argsort(loglikes)[::-1][:3]

array([3, 5, 4])

In [241]:
loglikes.index(2.1390214444154263)

3

In [246]:
np.array([1 / M for m in range(M)]) 

array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1])

In [247]:
np.array(1 / M for m in range(M)) 

array(<generator object <genexpr> at 0x10ce8a740>, dtype=object)

In [248]:
top_5 = np.argsort(loglikes)[::-1][:5]

In [249]:
top_5

array([3, 5, 4, 1, 2])

In [250]:
[loglikes[j] for j in top_5]

[2.1390214444154263,
 0.46622249235307717,
 0.17601708623957837,
 -0.08528746545069094,
 -0.1448665283708884]

In [251]:
alllog = np.random.randn(11)

In [252]:
alllog

array([ 0.64352306, -2.53302565, -1.4435365 ,  1.08938791, -0.96704257,
       -0.78098078,  2.02874803,  1.05620112,  0.59673062, -0.86688606,
        0.09527883])

In [253]:
logmax = alllog.max(axis=0, keepdims=True)

In [254]:
logmax

array([2.02874803])

In [256]:
def sumexp(a, b, axis=0):
  return np.exp(a-b).sum(axis=axis, keepdims=True)

In [257]:
logmax + np.log(sumexp(alllog, logmax))

array([2.98798645])

In [263]:
log_ps = np.random.randn(8, 62)
x = np.random.randn(62, 13)

In [264]:
ps = np.exp(log_ps)
maxp = log_ps.max(1, keepdims=True)

In [277]:
((ps @ x) / (maxp + sumexp(log_ps, maxp, 1)))

array([[ 3.01578855, -0.69067124,  0.31269408, -0.64624526, -0.77619725,
         0.62022028,  2.74405952, -0.7547602 ,  1.15369184, -2.72229314,
        -0.41718977, -0.03224585,  1.87934234],
       [ 1.01949305, -0.36311768, -0.06806462,  0.18111477, -0.15720911,
        -0.92801625,  0.70447244, -0.57180222, -0.07783894, -0.72452267,
        -0.63399019,  0.69046952,  0.14304502],
       [ 2.67745131, -1.41906821,  0.40484342, -0.57541226, -0.62273165,
         1.22615387,  3.44838381, -2.07776653,  0.0381762 , -0.07680419,
         0.75542981,  0.30273354, -0.34712492],
       [-0.25364952, -1.52668922, -0.81006218,  1.45105343,  0.67882116,
        -0.5446398 ,  2.57512771, -1.8481369 ,  0.42546174, -1.18079973,
        -1.04269969,  2.07421036,  0.36537684],
       [ 0.20246086, -0.38059677, -1.37373379, -0.32828783, -0.77073626,
         0.14128527, -0.96490666, -1.36833908,  0.05120005, -0.71138638,
        -1.21783608, -0.64518137,  1.05237276],
       [-0.27268907, -1.559833

In [278]:
((ps @ x) / (maxp + logsumexp(log_ps)))

array([[ 3.31785497, -0.75985003,  0.34401404, -0.71097426, -0.85394247,
         0.68234258,  3.01890911, -0.83035825,  1.26924754, -2.99496256,
        -0.45897619, -0.03547564,  2.06758041],
       [ 2.36816146, -0.84347932, -0.15810604,  0.42070813, -0.36517812,
        -2.1556717 ,  1.63640593, -1.32822874, -0.18081063, -1.68298024,
        -1.47268402,  1.6038788 ,  0.33227661],
       [ 3.7863248 , -2.00677904,  0.57251039, -0.81372076, -0.8806376 ,
         1.73396872,  4.87654102, -2.93827899,  0.05398698, -0.10861285,
         1.06829305,  0.42811143, -0.49088762],
       [-0.39616192, -2.38445599, -1.26519372,  2.26632441,  1.06021525,
        -0.8506444 ,  4.0219572 , -2.8865083 ,  0.66450643, -1.8442293 ,
        -1.62853808,  3.23960061,  0.57066297],
       [ 0.35038677, -0.65867583, -2.37743803, -0.56814791, -1.33386666,
         0.24451387, -1.66990564, -2.36810174,  0.08860883, -1.23115341,
        -2.10763529, -1.11657639,  1.82127792],
       [-0.37054957, -2.119613

In [268]:
log_ps.max(1)

array([2.57345944, 1.47650823, 2.29154433, 2.17462916, 1.89489675,
       2.29730971, 1.71316416, 3.34520039])

In [274]:
log_ps.max(1, keepdims=True) == np.max(log_ps, 1, keepdims=True)

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True]])

In [287]:
omega = np.random.randn(m, 1)
# log_omega = np.log(np.tile(omega, (1, t)))  # (M, T)
log_sum = logsumexp(log_Bs, b=omega, axis=0)  # (T, )

In [282]:
log_Bs = np.random.randn(m, t)

In [289]:
omega

array([[ 1.3481541 ],
       [-0.44065248],
       [-0.02347122],
       [-0.70256166],
       [ 1.03364048],
       [ 0.08840937],
       [-0.7238759 ],
       [-0.8221972 ],
       [ 0.71651224],
       [ 0.18338522]])

In [290]:
alllog = log_Bs + omega
logmax = alllog.max(axis=0, keepdims=True)

In [294]:
(logmax + np.log(sumexp(alllog, logmax)))

array([[2.7242809 , 3.52327009, 2.61779044, 2.37006498, 2.88791092,
        2.46392849, 2.478902  , 2.86362372, 3.27134737, 3.24348703,
        2.55898852, 2.83612203, 3.28773218]])

In [293]:
log_sum

array([ 0.05340123,  1.9270936 ,         nan,         nan,         nan,
       -0.12545284,  0.7340919 ,         nan,         nan,  1.2909893 ,
       -1.73349112,         nan,  1.3660105 ])

In [295]:
def logsumexp(x):
    c = x.max()
    return c + np.log(np.sum(np.exp(x - c)))

In [296]:
def sumexp(a, b, axis=0):
    return np.exp(a-b).sum(axis=axis, keepdims=True)

In [306]:
logsumexp(log_ps)

6.626930402502694

In [307]:
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [308]:
from scipy.special import logsumexp

In [316]:
alllog.shape

(10, 13)

In [319]:
log_Bs.shape

(10, 13)

In [320]:
omega.shape

(10, 1)

In [321]:
alllog = log_Bs + np.log(omega)
logmax = alllog.max(axis=0, keepdims=True)
log_pmx = alllog - logmax - np.log(sumexp(alllog, logmax))

<ipython-input-321-526bfd4f0279>:1: RuntimeWarning: invalid value encountered in log
  alllog = log_Bs + np.log(omega)


In [322]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 3)

In [333]:
x.shape

(62, 13)

In [346]:
sigma = np.random.randn(13)

In [350]:
a

array([[-0.62424888,  1.66422886,  0.22540839],
       [-1.11311261,  2.25633498,  2.19964679],
       [-0.72607541, -0.32102636, -0.52739072]])

In [351]:
b

array([[-2.47988658, -0.79532693, -0.46498397],
       [ 0.33203917, -0.83984635, -0.05402705],
       [ 0.0109782 ,  1.59380118,  1.6304995 ]])

In [352]:
a * b

array([[ 1.54806643, -1.32360603, -0.10481129],
       [-0.36959698, -1.89497469, -0.11884042],
       [-0.007971  , -0.5116522 , -0.85991031]])

In [369]:
s = ['sbs', 'kbs', 'mbc', 'jtbc']

In [370]:
s.insert(0, '<s>')

In [371]:
s.insert(len(s), '</s>')

In [372]:
s

['<s>', 'sbs', 'kbs', 'mbc', 'jtbc', '</s>']

In [394]:
R = np.zeros((6, 8))

In [395]:
R

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [396]:
R[:, 0] = np.arange(len(R[:, 0]))
R[0, :] = np.arange(len(R[0, :]))

In [397]:
len(R[:, 0]), len(R[0, :])

(6, 8)

In [400]:
np.array([5, 4, 3]).min() + 1

4

In [404]:
np.average([1, 2, 3])

2.0

In [413]:
sigma.shape

(13,)

In [410]:
sigma.reshape(1, d).shape

(1, 13)

In [412]:
x.shape

(62, 13)

In [435]:
a = np.einsum("ij,ji->i", x / sigma, x.T)

In [436]:
b = (((x * x)/sigma).sum(axis=1))

In [445]:
np.einsum('ij,ji->i', x / sigma, x.T) / 2 == np.einsum('ij,ji->i', x / sigma, x.T) * 0.5

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True])

In [447]:
mu = np.random.randn(d)

In [442]:
no = []
for i in range(a.shape[0]):
    if a[i] != b[i]:
        no.append((i, a[i], b[i]))

mu.shape

In [448]:
mu.shape

(13,)

In [449]:
(x / sigma) @ mu == np.dot((x / sigma), mu)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True])